const items = [
    "how to learn dsa",
    "Hello World",
    "apple",
    "app",
    "Avishkaar",
    "How to install Anaconda",
    "How to create youtube shorts",
    "Happy Coding",
    "What is Dark Web",
    "Learn DSA with Pepcoding",
    "Nados Info",
    "Learn with NADOS",
    "Mango",
    "Application",
    "What is WWW.",
    "Inner engineering",
    "World Wide Web",
    "Random Access Memory",
    "Roadways info",
    "Placement",
    "how to prepare for product based companies",
    "what is fullform of",
    "what is fullform of ISRO",
    "what is the Barmuda triangle",
    "'Be positive' essay",
    "Uses of Sulphur",
    "Today's Tagline",
    "Dart",
    "Dart Programming",
    "Don 2",
    "DareToCompete",
    "Do's and dont's",
    "The Sun",
    "The Universe",
    "The University",
    "Divide and Rule",
    "Check your Brain age",
    "Concept of Relativity",
    "Concept of Physics",
    "Clear your doubt",
    "Cat",
    "cat",
    "divide and rule",
    "dart",
    "python",
    "c programming",
    "Application",
    "c++ programming concept",
    "Java",
    "java",
    "google",
    "good morning quotes",
    "good quotes",
    "second world war",
    "Good morning",
    "vander waal force",
    "mango",
    "Mango",
    "Most important topics",
    "most important topics for board",
    "Most important topics",
    "flutter",
    "Go",
    "Apple",
    "Golang",
    "go programming language",
    "xylem and phloyem",
    "zoo",
    "wildlife",
    "as well as",
    "Amazing concept",
    "amazing concept",
    "Largest",
    "Low intensity",
    "low intensity",
    "trie",
    "timeline",
    "k-mean clustering",
    "knowledge",
    "knowledge is your power",
    "Know yourself",
    "Examples of",
    "starting of life on the earth",
    "book your show",
    "cookies",
    "domain",
    "element",
    "fear of",
    "gear up",
    "honest talk",
    "is it clear",
    "jk",
    "know your potential",
    "lemon",
    "mongo",
    "note that",
    "operation",
    "pick the correct option",
    "quick",
    "rare element on the earth",
    "seven color of",
    "test your knowledge",
    "use of",
    "vacobulary in",
    "well explained",
    "xyz",
    "yes, start",
    "zone of",
    "Book the ticket",
    "Conceptual understanding",
    "Data analysis",
    "Engagement incremental",
    "Fog and mist",
    "Gear up your progress",
    "How to start coding",
    "Is it right",
    "Jest",
    "K is symbol of",
    "Lotus tample",
    "Magnify",
    "No SQL",
    "Okay means",
    "P-block element",
    "Quartz",
    "Rest state",
    "Seven colour of ",
    "There are how many type of",
    "Uses of",
    "V s l",
    "Wax ",
    "X R",
    "Year ",
    "Zone",
];